import type { Post } from './types';

export const samplePosts: Post[] = [
  {
    id: '1',
    title: 'Cozy Room for Rent',
    subtitle: 'Downtown City',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Alice',
    ownerAvatar: 'A',
    aiHint: 'cozy room',
  },
  {
    id: '2',
    title: 'Vintage Car Available',
    subtitle: 'Red Convertible, 1965',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Bob',
    ownerAvatar: 'B',
    aiHint: 'vintage car',
  },
  {
    id: '3',
    title: 'Beachside House',
    subtitle: 'Ocean view property',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Charlie',
    ownerAvatar: 'C',
    aiHint: 'beach house',
  },
  {
    id: '4',
    title: 'Mountain Land Plot',
    subtitle: 'Secluded land in hills',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Dave',
    ownerAvatar: 'D',
    aiHint: 'mountain landscape',
  },
  {
    id: '5',
    title: 'Downtown Apartment',
    subtitle: 'Modern 2-bedroom apartment',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Eve',
    ownerAvatar: 'E',
    aiHint: 'modern apartment',
  },
  {
    id: '6',
    title: 'Cyberpunk Loft',
    subtitle: 'High-tech urban living',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Faye',
    ownerAvatar: 'F',
    aiHint: 'cyberpunk city',
  },
  {
    id: '7',
    title: 'Classic Sailboat',
    subtitle: 'Ready for the open sea',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Grace',
    ownerAvatar: 'G',
    aiHint: 'sailboat sunset',
  },
  {
    id: '8',
    title: 'Artisanal Coffee Shop',
    subtitle: 'Fully equipped, prime location',
    imageUrl: 'https://placehold.co/600x400',
    owner: 'Heidi',
    ownerAvatar: 'H',
    aiHint: 'coffee shop',
  },
];
